name: conduit_core
version: 5.1.3
publish_to: none
description: This is the core of the framework.
home: https://www.theconduit.dev
repository: https://github.com/conduit-dart/conduit
issue_tracker: https://github.com/conduit-dart/conduit/issues

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  analyzer: ^6.5.0
  args: ^2.4.2
  collection: ^1.18.0
  conduit_common: 
    # path: ../common
    git:
      url: git@github.com:phan-tech-ltd/conduit.git
      path: packages/common
  conduit_config: 
    # path: ../config
    git:
      url: git@github.com:phan-tech-ltd/conduit.git
      path: packages/config
  conduit_isolate_exec: 
    # path: ../isolate_exec
    git:
      url: git@github.com:phan-tech-ltd/conduit.git
      path: packages/isolate_exec
  conduit_open_api: 
    # path: ../open_api
    git:
      url: git@github.com:phan-tech-ltd/conduit.git
      path: packages/open_api
  conduit_password_hash: 
    # path: ../password_hash
    git:
      url: git@github.com:phan-tech-ltd/conduit.git
      path: packages/password_hash
  conduit_runtime: 
    # path: ../runtime
    git:
      url: git@github.com:phan-tech-ltd/conduit.git
      path: packages/runtime
  crypto: ^3.0.3
  io: ^1.0.4
  logging: ^1.2.0
  meta: ^1.12.0
  path: ^1.9.0
  postgres: ^3.1.1
  pub_semver: ^2.1.4
  recase: ^4.1.0
  yaml: ^3.1.2

dev_dependencies:
  conduit_postgresql:
    path: ../postgresql
  conduit_test:
    path: ../test_harness
  fs_test_agent:
    path: ../fs_test_agent
  http: ^1.2.1
  lints: ^4.0.0
  matcher: ^0.12.16+1
  mockito: ^5.4.4
  test: ^1.25.2
  web_socket_channel: ^3.0.0
