name: conduit_open_api
version: 5.1.3
publish_to: none
description: Data structures for OpenAPI (Swagger) specification. Reads and writes JSON specifications.
home: https://www.theconduit.dev
repository: https://github.com/conduit-dart/conduit
issue_tracker: https://github.com/conduit-dart/conduit/issues

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  conduit_codable: 
    # path: ../codable
    git:
      url: git@github.com:phan-tech-ltd/conduit.git
      path: packages/codable
  meta: ^1.12.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.2
